# CricIntel AI - Data Cleaning

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
matches = pd.read_csv("../../data/raw/Matches.csv")
customers = pd.read_csv("../../data/raw/Customers.csv")
ticket_sales = pd.read_csv("../../data/raw/Ticket_Sales.csv")

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [4]:
def data_quality_summary(df, dataset_name):
    summary = {
        "Dataset": dataset_name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    }
    return summary

In [5]:
## quality report
quality_report = pd.DataFrame([
    data_quality_summary(matches, "Matches"),
    data_quality_summary(customers, "Customers"),
    data_quality_summary(ticket_sales, "Ticket Sales")
])

display(quality_report)

        Dataset    Rows  Columns  Missing Values  Duplicate Rows
0       Matches      74       12               0               0
1     Customers   12000       15               0               0
2  Ticket Sales  150000       10               0               0

In [6]:
## missing values
print("Missing Values - Matches")
display(matches.isnull().sum())

Missing Values - Matches

Match_ID            0
Match_Date          0
Season              0
Home_Team           0
Away_Team           0
Venue               0
City                0
Match_Type          0
Stadium_Capacity    0
VIP_Capacity        0
Premium_Capacity    0
Economy_Capacity    0
dtype: int64

In [7]:
print("Missing Values - Ticket Sales")
display(ticket_sales.isnull().sum())

Missing Values - Ticket Sales

Ticket_ID         0
Customer_ID       0
Match_ID          0
Booking_Date      0
Seat_Category     0
Ticket_Price      0
Quantity          0
Total_Amount      0
Payment_Method    0
Booking_Status    0
dtype: int64

In [8]:
## Check Duplicate Records matchess
print("Duplicate Records - Matches")

duplicate_matches = matches[matches.duplicated()]

print(f"Total Duplicate Records: {duplicate_matches.shape[0]}")

display(duplicate_matches)

Duplicate Records - Matches
Total Duplicate Records: 0

Empty DataFrame
Columns: [Match_ID, Match_Date, Season, Home_Team, Away_Team, Venue, City, Match_Type, Stadium_Capacity, VIP_Capacity, Premium_Capacity, Economy_Capacity]
Index: []

In [9]:
## Check duplicate records customer
print("Duplicate Records - Customers")

duplicate_customers = customers[customers.duplicated()]

print(f"Total Duplicate Records: {duplicate_customers.shape[0]}")

display(duplicate_customers)

Duplicate Records - Customers
Total Duplicate Records: 0

Empty DataFrame
Columns: [Customer_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, City, State, Favorite_Team, Occupation, Annual_Income, Loyalty_Tier, Email, Phone, Registration_Date]
Index: []

In [10]:
# Check dupllicate records for ticket sales 
print("Duplicate Records - Ticket Sales")

duplicate_ticket_sales = ticket_sales[ticket_sales.duplicated()]

print(f"Total Duplicate Records: {duplicate_ticket_sales.shape[0]}")

display(duplicate_ticket_sales)

Duplicate Records - Ticket Sales
Total Duplicate Records: 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [11]:
## Validating match ids
print("Checking Unique Match IDs")

print("Total Match IDs :", matches["Match_ID"].count())
print("Unique Match IDs:", matches["Match_ID"].nunique())

Checking Unique Match IDs
Total Match IDs : 74
Unique Match IDs: 74

In [12]:
## valiprint("Checking Unique Customer IDs")
print("Checking Unique Customer IDs")

print("Total Customer IDs :", customers["Customer_ID"].count())
print("Unique Customer IDs:", customers["Customer_ID"].nunique())

Checking Unique Customer IDs
Total Customer IDs : 12000
Unique Customer IDs: 12000

In [13]:
## Validate Ticket IDs
print("Checking Unique Ticket IDs")

print("Total Ticket IDs :", ticket_sales["Ticket_ID"].count())
print("Unique Ticket IDs:", ticket_sales["Ticket_ID"].nunique())

Checking Unique Ticket IDs
Total Ticket IDs : 150000
Unique Ticket IDs: 150000

In [14]:
## Validating datatypes
print("Matches Data Types")
display(matches.dtypes)

print("\nCustomers Data Types")
display(customers.dtypes)

print("\nTicket Sales Data Types")
display(ticket_sales.dtypes)

Matches Data Types

Match_ID            object
Match_Date          object
Season              object
Home_Team           object
Away_Team           object
Venue               object
City                object
Match_Type          object
Stadium_Capacity     int64
VIP_Capacity         int64
Premium_Capacity     int64
Economy_Capacity     int64
dtype: object

Customers Data Types

Customer_ID          object
First_Name           object
Last_Name            object
Gender               object
Age                   int64
Date_of_Birth        object
City                 object
State                object
Favorite_Team        object
Occupation           object
Annual_Income         int64
Loyalty_Tier         object
Email                object
Phone                 int64
Registration_Date    object
dtype: object

Ticket Sales Data Types

Ticket_ID         object
Customer_ID       object
Match_ID          object
Booking_Date      object
Seat_Category     object
Ticket_Price       int64
Quantity           int64
Total_Amount       int64
Payment_Method    object
Booking_Status    object
dtype: object

In [15]:
# Create working copies for data cleaning

matches_clean = matches.copy()
customers_clean = customers.copy()
ticket_sales_clean = ticket_sales.copy()

print("Working copies created successfully.")

Working copies created successfully.

In [16]:
# Convert date columns

matches_clean["Match_Date"] = pd.to_datetime(matches_clean["Match_Date"])

customers_clean["Registration_Date"] = pd.to_datetime(
    customers_clean["Registration_Date"]
)

ticket_sales_clean["Booking_Date"] = pd.to_datetime(
    ticket_sales_clean["Booking_Date"]
)

print("Date conversion completed.")

Date conversion completed.

In [17]:
print(matches_clean["Match_Date"].dtype)

print(customers_clean["Registration_Date"].dtype)

print(ticket_sales_clean["Booking_Date"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]

In [18]:
print("Gender Values")

display(customers_clean["Gender"].value_counts())

Gender Values

Gender
Male      7749
Female    4251
Name: count, dtype: int64

In [19]:
print("Loyalty Tier")

display(customers_clean["Loyalty_Tier"].value_counts())

Loyalty Tier

Loyalty_Tier
Bronze      6086
Silver      3529
Gold        1795
Platinum     590
Name: count, dtype: int64

In [20]:
print("Booking Status")

display(ticket_sales_clean["Booking_Status"].value_counts())

Booking Status

Booking_Status
Confirmed    142504
Cancelled      7496
Name: count, dtype: int64

In [21]:
print("Payment Methods")

display(ticket_sales_clean["Payment_Method"].value_counts())

Payment Methods

Payment_Method
UPI            67378
Credit Card    37783
Debit Card     30028
Net Banking    14811
Name: count, dtype: int64

In [22]:
print("Seat Categories")

display(ticket_sales_clean["Seat_Category"].value_counts())

Seat Categories

Seat_Category
Economy    89839
Premium    45015
VIP        15146
Name: count, dtype: int64

In [23]:
invalid_quantity = ticket_sales_clean[
    ticket_sales_clean["Quantity"] <= 0
]

print("Invalid Ticket Quantity :", len(invalid_quantity))

display(invalid_quantity)

Invalid Ticket Quantity : 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [24]:
invalid_price = ticket_sales_clean[
    ticket_sales_clean["Ticket_Price"] <= 0
]

print("Invalid Ticket Price :", len(invalid_price))

display(invalid_price)

Invalid Ticket Price : 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [25]:
invalid_amount = ticket_sales_clean[
    ticket_sales_clean["Total_Amount"] <= 0
]

print("Invalid Total Amount :", len(invalid_amount))

display(invalid_amount)

Invalid Total Amount : 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [26]:
# Validate Customer IDs

invalid_customers = ticket_sales_clean[
    ~ticket_sales_clean["Customer_ID"].isin(customers_clean["Customer_ID"])
]

print("Invalid Customer IDs :", len(invalid_customers))

display(invalid_customers)

Invalid Customer IDs : 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [27]:
# Validate Match IDs

invalid_matches = ticket_sales_clean[
    ~ticket_sales_clean["Match_ID"].isin(matches_clean["Match_ID"])
]

print("Invalid Match IDs :", len(invalid_matches))

display(invalid_matches)

Invalid Match IDs : 0

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Match_ID, Booking_Date, Seat_Category, Ticket_Price, Quantity, Total_Amount, Payment_Method, Booking_Status]
Index: []

In [30]:
# Clean email addresses

customers_clean["Email"] = (
    customers_clean["Email"]
    .str.strip()
    .str.replace("’", "", regex=False)
    .str.replace("'", "", regex=False)
)

print("Email cleaning completed.")

Email cleaning completed.

In [31]:
# Validate Email Format

invalid_email = customers_clean[
    ~customers_clean["Email"].str.contains(
        r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",
        regex=True
    )
]

print("Invalid Email Addresses :", len(invalid_email))

display(invalid_email)

Invalid Email Addresses : 0

Empty DataFrame
Columns: [Customer_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, City, State, Favorite_Team, Occupation, Annual_Income, Loyalty_Tier, Email, Phone, Registration_Date]
Index: []

In [32]:
# Validate Phone Numbers

invalid_phone = customers_clean[
    customers_clean["Phone"].astype(str).str.len() != 10
]

print("Invalid Phone Numbers :", len(invalid_phone))

display(invalid_phone)

Invalid Phone Numbers : 0

Empty DataFrame
Columns: [Customer_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, City, State, Favorite_Team, Occupation, Annual_Income, Loyalty_Tier, Email, Phone, Registration_Date]
Index: []

In [33]:
# Validate Registration Dates

future_registration = customers_clean[
    customers_clean["Registration_Date"] > pd.Timestamp.today()
]

print("Future Registration Dates :", len(future_registration))

display(future_registration)

Future Registration Dates : 0

Empty DataFrame
Columns: [Customer_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, City, State, Favorite_Team, Occupation, Annual_Income, Loyalty_Tier, Email, Phone, Registration_Date]
Index: []

In [34]:
# Validate Match Year

invalid_match_year = matches_clean[
    matches_clean["Match_Date"].dt.year != 2026
]

print("Invalid Match Year :", len(invalid_match_year))

display(invalid_match_year)

Invalid Match Year : 0

Empty DataFrame
Columns: [Match_ID, Match_Date, Season, Home_Team, Away_Team, Venue, City, Match_Type, Stadium_Capacity, VIP_Capacity, Premium_Capacity, Economy_Capacity]
Index: []

In [35]:
# Validate Stadium Capacity

capacity_check = matches_clean[
    (
        matches_clean["VIP_Capacity"]
        + matches_clean["Premium_Capacity"]
        + matches_clean["Economy_Capacity"]
    )
    != matches_clean["Stadium_Capacity"]
]

print("Capacity Mismatch :", len(capacity_check))

display(capacity_check)

Capacity Mismatch : 0

Empty DataFrame
Columns: [Match_ID, Match_Date, Season, Home_Team, Away_Team, Venue, City, Match_Type, Stadium_Capacity, VIP_Capacity, Premium_Capacity, Economy_Capacity]
Index: []

In [36]:
# Final Data Quality Report

quality_summary = pd.DataFrame({
    "Validation": [
        "Missing Values",
        "Duplicate Rows",
        "Invalid Customer IDs",
        "Invalid Match IDs",
        "Invalid Emails",
        "Invalid Phone Numbers",
        "Future Registration Dates",
        "Invalid Match Year",
        "Capacity Mismatch"
    ],
    "Issues Found": [
        matches_clean.isnull().sum().sum()
        + customers_clean.isnull().sum().sum()
        + ticket_sales_clean.isnull().sum().sum(),

        matches_clean.duplicated().sum()
        + customers_clean.duplicated().sum()
        + ticket_sales_clean.duplicated().sum(),

        len(invalid_customers),
        len(invalid_matches),
        len(invalid_email),
        len(invalid_phone),
        len(future_registration),
        len(invalid_match_year),
        len(capacity_check)
    ]
})

display(quality_summary)

                  Validation  Issues Found
0             Missing Values             0
1             Duplicate Rows             0
2       Invalid Customer IDs             0
3          Invalid Match IDs             0
4             Invalid Emails             0
5      Invalid Phone Numbers             0
6  Future Registration Dates             0
7         Invalid Match Year             0
8          Capacity Mismatch             0

In [37]:
# Overall Validation Status

if quality_summary["Issues Found"].sum() == 0:
    print("All data quality checks passed successfully.")
else:
    print("Data quality issues detected. Review the validation report.")

All data quality checks passed successfully.

#### SUMMARY 
## Data Cleaning Completed

The following validations were successfully performed:

- Missing Value Check
- Duplicate Record Check
- Primary Key Validation
- Foreign Key Validation
- Data Type Validation
- Email Format Validation
- Phone Number Validation
- Date Validation
- Stadium Capacity Validation
- Business Rule Validation

The datasets passed all quality checks and are ready for Exploratory Data Analysis (EDA).